version: "3.8"
services:

  # PostgreSQL DB for storing video metadata
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=youtube_clone
    ports:
      - '5432:5432'
    volumes: 
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data      
    
  # Minio S3 server for object storage
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio-data:/data

  # Elastic search node for providing very fast search results
  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
  # ES setup for configuring the index
  es-setup:
    image: curlimages/curl:8.5.0
    depends_on:
      - elasticsearch
    entrypoint: >
      sh -c "
        echo 'Waiting for Elasticsearch...';
        until curl -s http://elasticsearch:9200 >/dev/null; do sleep 2; done;
        echo 'Creating index...';
        curl -X PUT http://elasticsearch:9200/videos
          -H 'Content-Type: application/json'
          -d @/config/videos-index.json;
        echo 'Index created';
      "
    volumes:
      - ./es-config:/config

volumes:
  pgdata:
    driver: local
  esdata:
    driver: local